volumes:
    postgres-volume:
    redis-volume:
    kafka-volume:
    filebeat-volume:
    es-volume:


networks:
    test-task-wallet-net:
        name: "test-task-wallet-net"
        driver: bridge

services:

    db:
        image: postgres:${POSTGRES_VERSION}
        container_name: "test-task-wallet-database"
        env_file:
            - config.env
        networks:
            - test-task-wallet-net
        ports:
            - ${POSTGRES_PORT}:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 1s
            timeout: 60s
            retries: 60
        restart: always
        volumes:
            - postgres-volume:/var/lib/postgresql/data


    redis:
        image: redis:${REDIS_VERSION}
        container_name: "test-task-wallet-redis"
        networks:
            - test-task-wallet-net
        ports:
            - ${REDIS_PORT}:6379
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
        volumes:
            - redis-volume:/data

    zookeeper:
        image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
        container_name: zookeeper
        ports:
            - "22181:2181"
        networks:
            - test-task-wallet-net
        env_file:
            - config.env

    kafka:
        image: confluentinc/cp-kafka:${KAFKA_VERSION}
        container_name: kafka
        restart: always
        ports:
            - "19092:9092"
            - "9997:9997"
        networks:
            - test-task-wallet-net
        depends_on:
            - zookeeper
        env_file:
            - config.env
        volumes:
            - kafka-volume:/bitnami/kafka

    filebeat:
        image: elastic/filebeat:8.10.2
        container_name: filebeat
        user: "1000:1000"
        restart: unless-stopped
        depends_on:
            - elasticsearch
            - kafka
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./filebeat-volume:/usr/share/filebeat/data:z
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./filebeat-logs:/usr/share/filebeat/logs
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=changeme
            - KAFKA_HOSTS=kafka:9093
        networks:
            - test-task-wallet-net

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=true
            - xpack.security.autoconfiguration.enabled=true
            - ELASTIC_PASSWORD=changeme
        volumes:
            - es-volume:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - test-task-wallet-net
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
            interval: 10s
            timeout: 10s
            retries: 20

    kibana:
        image: kibana:8.10.2
        ports:
            - "5601:5601"
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL215LWtpYmFuYS10b2tlbjo1eXROY0w4Y1NnLW1vdWxKU2FPckZn
        depends_on:
            - elasticsearch
        networks:
            - test-task-wallet-net
        restart: always

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "test-task-wallet-app"
        env_file:
            - config.env
        environment:
            POSTGRES_HOST: db
            REDIS_HOST: redis
            POSTGRES_PORT: 5432
            REDIS_PORT: 6379
        ports:
            - ${SERVER_PORT_HTTP}:${SERVER_PORT_HTTP}
        networks:
            - test-task-wallet-net
        restart: always
        depends_on:
            - db
            - redis
            - kafka
            - zookeeper